Flutter Component 0.0.2
egovernments/DIGIT-UI-LIBRARIES pull request #119
Opened 2024-09-03 12:22 UTC by rachana-egov

2024-09-20 07:37 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/table_cell.dart
> +        );
resolved

2024-09-20 07:40 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/theme/ComponentTheme/bread_crumb_theme.dart
> +  }
done

2024-09-20 07:40 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_search_bar.dart
> +}
did that to make it more customizable

2024-09-20 07:40 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_tree_select_dropdown.dart
> +///),
done

2024-09-20 07:42 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_dob_picker.dart
> +  }
age cann't be more than current date

2024-09-20 07:43 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_otp.dart
> +  }
done

2024-09-20 07:44 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_base_form_input.dart
>      myFocusNode.dispose();
done

2024-10-03 07:25 UTC, naveen-egov requested changes
Please make the necessary changes as requested

2024-10-03 07:25 UTC, naveen-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/upload_image.dart
> +                  label: widget.captureText ??'Capture',
use i18 code

2024-10-03 07:25 UTC, naveen-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/helper_widget/overlay_dropdown.dart
> +                            color: const Color(0x26000000), // #00000026
Color should be read from Themes

2024-10-03 07:25 UTC, naveen-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/molecules/digit_timeline_molecule.dart
> +    this.hideDetailText = 'Hide Details',
Use i18 codes

2024-10-03 07:25 UTC, naveen-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/molecules/language_selection_card.dart
> +          fontSize: 16,
Font size should be read from Themes

2024-10-14 09:58 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/CHANGELOG.md
>  * test release.
updated with previous release,

2024-10-14 09:59 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/blocs/TimeSelectionBloc.dart
>            data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: false),
it is from params only

2024-10-14 10:33 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/constants/app_constants.dart
> +class Base{
done

2024-10-14 10:35 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/theme/ComponentTheme/action_card_theme.dart
> +      spacing: 24,
done

2024-10-14 10:38 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/utils/fileService/web_file_download.dart
> +      ..setAttribute("download", file.name)
that is html default down attribute

2024-10-14 10:39 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/utils/validators/file_validator.dart
> +          return validator.errorMessage ?? 'Invalid file type';
they case send a error message to localize and this is not a stateful class just a function

2024-10-14 10:47 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_back_button.dart
> +    this.backButtonText = 'Back',
done

2024-10-14 10:57 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/molecules/language_selection_card.dart
> +          fontSize: 16,
done

2024-10-14 11:49 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/molecules/digit_timeline_molecule.dart
> +    this.hideDetailText = 'Hide Details',
done

2024-10-15 05:41 UTC, naveen-egov approved these changes

2024-10-15 05:51 UTC, rachana-egov commented on flutter/digit-ui-components/digit_components/lib/widgets/atoms/digit_tag.dart
> +            ],
i have made sure that icon is not null in first check

2024-10-15 06:04 UTC, naveen-egov approved these changes

2024-10-15 06:06 UTC, naveen-egov approved these changes

2024-10-15 06:29 UTC, rachana-egov commented on react/ui-components/src/hoc/stories/DropDown.stories.js
resolved

2024-10-15 06:35 UTC, merged